modules/SignServer-war/src/java/org/signserver/web/SettingsBean.java
/*************************************************************************
 *                                                                       *
 *  SignServer: The OpenSource Automated Signing Server                  *
 *                                                                       *
 *  This software is free software; you can redistribute it and/or       *
 *  modify it under the terms of the GNU Lesser General Public           *
 *  License as published by the Free Software Foundation; either         *
 *  version 2.1 of the License, or any later version.                    *
 *                                                                       *
 *  See terms of license at gnu.org.                                     *
 *                                                                       *
 *************************************************************************/
package org.signserver.web;

import org.signserver.common.CompileTimeSettings;

/**
 * Bean exposing settings to the JSP pages.
 *
 * @author Markus Kilås
 * @version $Id: SettingsBean.java 1814 2011-08-08 12:03:28Z netmackan $
 */
public class SettingsBean {
    
    /** Key in signservercompile.properties. */
    private static final String WEBDOC_ENABLED = "webdoc.enabled";
    
    private CompileTimeSettings settings = CompileTimeSettings.getInstance();
    
    /**
     * @return If the web documentation is enabled. 
     */
    public boolean isWebDocEnabled() {
        final String enabled = settings.getProperty(WEBDOC_ENABLED);
        return enabled != null && Boolean.parseBoolean(enabled);
    }
}

modules/SignServer-war/web/index.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <link rel="stylesheet" href="publicweb.css" type="text/css"/>
        <title>SignServer</title>
    </head>
    <body>
        <div id="container1">
            <%@include file="WEB-INF/jspf/header.jspf" %>
            <jsp:useBean class="org.signserver.web.SettingsBean" id="settings"/>

            <h4 style="margin-top: 4em;">Local Resources</h4>
            <ul class="resourcesList">
                <li><a href="demo/">Signing Demo</a></li>
                <li><a href="healthcheck/signserverhealth">Health Check</a></li>
                <c:if test="${settings.webDocEnabled}">
                    <li><a href="doc/">Documentation</a></li>
                </c:if>
            </ul>

            <h4>Online Resources</h4>
            <ul class="resourcesList">
                <li><a href="http://www.signserver.org">SignServer Web Site</a></li>
            </ul>

            <%@include file="WEB-INF/jspf/footer.jspf" %>
        </div>
    </body>
</html>